<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sureshs-iMac" ignored="0" name="Car Loan Test Cases" tests="12" failures="1" timestamp="2020-04-13T19:15:40 EDT" time="0.069" errors="0">
  <testcase name="RestLoginTest" time="0.005" classname="listners.HomeLoanWithDataProvider"/>
  <testcase name="RestLoginTest" time="0.006" classname="listners.CarLoanTestCases"/>
  <testcase name="RestLoginTest" time="0.001" classname="listners.HomeLoanWithDataProvider"/>
  <testcase name="RestLoginTest" time="0.002" classname="listners.HomeLoanWithDataProvider"/>
  <testcase name="mobileLoginTest" time="0.002" classname="listners.HomeLoanWithDataProvider"/>
  <testcase name="enabledExample" time="0.002" classname="listners.CarLoanTestCases"/>
  <testcase name="paramterTest" time="0.001" classname="listners.HomeLoanWithDataProvider"/>
  <testcase name="webLoginTest" time="0.0" classname="listners.HomeLoanWithDataProvider"/>
  <testcase name="failingTest" time="0.006" classname="listners.CarLoanTestCases">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at listners.CarLoanTestCases.failingTest(CarLoanTestCases.java:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- failingTest -->
  <testcase name="webLoginTest" time="0.001" classname="listners.CarLoanTestCases"/>
  <testcase name="zTimeOutExample" time="0.004" classname="listners.CarLoanTestCases"/>
  <testcase name="mobileLoginTest" time="0.001" classname="listners.CarLoanTestCases"/>
</testsuite> <!-- Car Loan Test Cases -->
